[
    {
        "code": "1000",
        "title": "Product1",
        "type": "alcohol",
        "description": "Some decription",
        "price": 10,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": true, "value": 0.09 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1001",
        "title": "Product2",
        "type": "alcohol",
        "description": "Some decription",
        "price": 123,
        "rating": 4,
        "quantity": 109,
        "sale": { "status": true, "value": 0.09 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1002",
        "title": "Product3",
        "type": "alcohol",
        "description": "Some decription",
        "price": 67,
        "rating": 4,
        "quantity": 150,
        "sale": { "status": true, "value": 0.09 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1003",
        "title": "Product3",
        "type": "alcohol",
        "description": "Some decription",
        "price": 860,
        "rating": 5,
        "quantity": 10,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1004",
        "title": "Product4",
        "type": "alcohol",
        "description": "Some decription",
        "price": 92,
        "rating": 5,
        "quantity": 179,
        "sale": { "status": true, "value": 0.05 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1005",
        "title": "Product5",
        "type": "alcohol",
        "description": "Some decription",
        "price": 54,
        "rating": 4,
        "quantity": 83,
        "sale": { "status": true, "value": 0.09 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1006",
        "title": "Product6",
        "type": "alcohol",
        "description": "Some decription",
        "price": 34,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1007",
        "title": "Product7",
        "type": "meat",
        "description": "Some decription",
        "price": 603,
        "rating": 4,
        "quantity": 73,
        "sale": { "status": true, "value": 0.25 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1008",
        "title": "Product8",
        "type": "meat",
        "description": "Some decription",
        "price": 234,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": true, "value": 0.2 },
        "images": ["http://localhost:8080/cache/images/1734976138494milk_c.jpg"]
    },
    {
        "code": "1009",
        "title": "Product9",
        "type": "meat",
        "description": "Some decription",
        "price": 44,
        "rating": 5,
        "quantity": 92,
        "sale": { "status": true, "value": 0.2 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1010",
        "title": "Product10",
        "type": "meat",
        "description": "Some decription",
        "price": 824,
        "rating": 3,
        "quantity": 27,
        "sale": { "status": true, "value": 0.03 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1011",
        "title": "Product11",
        "type": "bread",
        "description": "Some decription",
        "price": 2,
        "rating": 5,
        "quantity": 995,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1012",
        "title": "Product12",
        "type": "bread",
        "description": "Some decription",
        "price": 12,
        "rating": 5,
        "quantity": 885,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1013",
        "title": "Product13",
        "type": "bread",
        "description": "Some decription",
        "price": 7,
        "rating": 4,
        "quantity": 359,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1014",
        "title": "Product14",
        "type": "bread",
        "description": "Some decription",
        "price": 10.6,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": true, "value": 0.02 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1015",
        "title": "Product15",
        "type": "cheese",
        "description": "Some decription",
        "price": 107,
        "rating": 4,
        "quantity": 12,
        "sale": { "status": true, "value": 0.02 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1016",
        "title": "Product16",
        "type": "cheese",
        "description": "Some decription",
        "price": 205,
        "rating": 3,
        "quantity": 104,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1017",
        "title": "Product17",
        "type": "cheese",
        "description": "Some decription",
        "price": 205,
        "rating": 4,
        "quantity": 17,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1018",
        "title": "Product18",
        "type": "cheese",
        "description": "Some decription",
        "price": 78,
        "rating": 4,
        "quantity": 22,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1019",
        "title": "Product19",
        "type": "cheese",
        "description": "Some decription",
        "price": 10,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": true, "value": 0.09 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1020",
        "title": "Product20",
        "type": "cheese",
        "description": "Some decription",
        "price": 10,
        "rating": 4,
        "quantity": 10,
        "sale": { "status": true, "value": 0.03 },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
    {
        "code": "1021",
        "title": "Product21",
        "type": "cheese",
        "description": "Some decription",
        "price": 16,
        "rating": 4,
        "quantity": 108,
        "sale": { "status": false },
        "images": ["http://localhost:8080/cache/images/1734976242325bread_c.jpg"]
    },
]